pipeline {
    agent none
    stages {
        stage('Back-end') {
            agent {
                docker { image 'maven:3.8.1-adoptopenjdk-11' }
            }
            steps {
                sh 'mvn --version'
            }
        }

        stage('Front-end') {
            agent {
                docker { image 'node:16-alpine' }
            }
            steps {
                sh 'node --version'
            }
        }

        stage('Java Application') {
            agent {
                docker { image 'openjdk:17-jdk-slim' }
            }
            steps {
                echo "Compiling and running HelloWorld.java in multi-agent folder..."
                sh 'javac multi-agent/HelloWorld.java'
                sh 'java -cp multi-agent HelloWorld'
            }
        }
    }
}
